services:
  - type: web
    name: knowledge-window-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: knowledge-window-db
          property: connectionString
    healthCheckPath: /docs
    autoDeploy: true
